### PR TITLE
Add in `activity` structs for `activity_table.json`

### PR DESCRIPTION
**Pull request by RenzVEVO**
Double check if I miss anything then let me know which part i need to change/edit.

### CODE REVIEW

**Review by Rhelvetican — CHANGES_REQUESTED** [review]
Remove `#[serde(rename_all = "camelCase")]` for empty / unit structs

**Comment by RenzVEVO** [comment]
Should be good now. Take another look when you have time.

**Review by RenzVEVO — COMMENTED** [review]
Here

**Review by Rhelvetican — CHANGES_REQUESTED** [review]
Actually let's remove any mention of it altogether as it's not used in the logic.

**Comment by RenzVEVO** [comment]
Here you go

**Review by Rhelvetican — APPROVED** [review]
Approved.

**Pull request merged**
